weights: yolov5s.pt
cfg: models/yolov5s.yaml
data: data/dataset3.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 200
batch_size: 32
imgsz: 608
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '1'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
name: ue92e_s
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
nohalf: false
quantize: false
BackendType: Tensorrt
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
sparse: false
sparse_rate: 0.001
save_dir: runs/train/ue92e_s2
